# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8852ba81692c21617b7411ee7ef4eba517ec3afc931ddd07e0ed807309bcddb6966a7c08c5a889c5a7817d4f4a3462a2c838c8ab31f8399f038f951af66ba8d

test:
  secret_key_base: 80dd3dbe33f276be6cc958bb6faf382d3e55b24dcce070564d9e235d08f507bc7a257066f53940032bbbdd5c54a28df2060575672a1842e5ddd0907536602a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
